# Generated by Django 6.0.7 on 2026-08-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parkinglot_vehicle_capacities'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='occupied_accessibility',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='occupied_cars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='occupied_motorcycles',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
