# Generated by Django 6.0.7 on 2026-08-30 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parkinglot_occupied_accessibility_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='occupied_spaces',
        ),
    ]
