# Generated by hand for Sprint 2 — FR16, FR17, FR26 (mapa interactivo por espacio)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_parkinglot_occupied_spaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='layout_image',
            field=models.ImageField(
                blank=True,
                help_text=(
                    'Croquis/plano de fondo sobre el que se ubican los espacios '
                    '(ParkingSpot) usando posiciones porcentuales (pos_x, pos_y).'
                ),
                null=True,
                upload_to='parking_layouts/',
                verbose_name='Imagen del plano',
            ),
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ej: A1, B12, M03', max_length=10)),
                ('vehicle_type', models.CharField(
                    choices=[('car', 'Carro'), ('motorcycle', 'Moto'), ('accessibility', 'PMR')],
                    default='car', max_length=20,
                )),
                ('pos_x', models.DecimalField(
                    decimal_places=2, max_digits=5,
                    help_text='Posición horizontal en porcentaje (0-100) sobre el plano.',
                    verbose_name='Posición X (%)',
                )),
                ('pos_y', models.DecimalField(
                    decimal_places=2, max_digits=5,
                    help_text='Posición vertical en porcentaje (0-100) sobre el plano.',
                    verbose_name='Posición Y (%)',
                )),
                ('status', models.CharField(
                    choices=[('empty', 'Vacío'), ('occupied', 'Ocupado'), ('unknown', 'No se sabe')],
                    default='unknown', max_length=20,
                )),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('lot', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='spots', to='core.parkinglot',
                )),
            ],
            options={
                'ordering': ['label'],
                'unique_together': {('lot', 'label')},
            },
        ),
    ]
