# Generated by Django 6.0.7 on 2026-09-22 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_parkinglotnotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Título de la regla (ej: 'Pico y placa')", max_length=200)),
                ('description', models.TextField(help_text='Descripción detallada de la regla')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.parkinglot')),
            ],
            options={
                'verbose_name': 'Regla de parqueadero',
                'verbose_name_plural': 'Reglas de parqueaderos',
                'ordering': ['id'],
            },
        ),
    ]
