# Generated by Django 6.0.7 on 2026-09-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_lot_location_aliases_and_favorites'),
        ('core', '0011_parkingrule'),
    ]

    operations = [
    ]
