# Generated by Django 6.0.7 on 2026-09-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20260923_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingrule',
            name='title',
        ),
        migrations.AlterField(
            model_name='parkingrule',
            name='description',
            field=models.TextField(help_text='Descripción de la regla'),
        ),
    ]
