# Generated by Django 6.0.7 on 2026-08-30 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_parkinglot_vehicle_capacities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('available', 'Espacio Disponible (FR21)'), ('occupied', 'Espacio Ocupado (FR22)'), ('incorrect', 'Información Incorrecta (FR30)')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detalle opcional (FR30)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de revisión'), ('valid', 'Validado (FR34)'), ('invalid', 'Inválido/Eliminado (FR32)')], default='pending', max_length=20)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.parkinglot')),
            ],
        ),
    ]
