# Generated by Django 6.0.7 on 2026-08-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingreport',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Carro'), ('motorcycle', 'Moto'), ('accessibility', 'PMR'), ('general', 'No especificado')], default='general', max_length=20),
        ),
    ]
